# Generated by Django 6.0.3 on 2026-05-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_in_bulk_app', '0002_benefit_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
